name: "Prepare External Packages"
inputs:
  build_type:
    required: false
    default: basic
    type: string
  cache-hit:
    required: true
    default: false
    type: bool
  os:
    required: false
    default: ubuntu-latest
    type: string

runs:
  using: "composite"
  steps:
    - name: Install External packages 
      if: ${{ ( inputs.build_type == 'basic' ) && ( inputs.cache-hit != 'true' ) && ( inputs.os == 'ubuntu-latest' ) }}
      shell: bash
      run: |
        cd $ISSM_DIR/externalpackages/triangle && ./install-linux.sh
        cd $ISSM_DIR/externalpackages/m1qn3    && ./install-linux.sh
        cd $ISSM_DIR/externalpackages/petsc    && ./install-3.21-linux.sh
        cd $ISSM_DIR/externalpackages/semic    && ./install.sh

    - name: Install External packages for AD
      if: ${{ ( inputs.build_type == 'codipack' ) && ( inputs.cache-hit != 'true' ) && ( inputs.os == 'ubuntu-latest' ) }}
      shell: bash
      run: |
        cd $ISSM_DIR/externalpackages/triangle   && ./install-linux.sh
        cd $ISSM_DIR/externalpackages/m1qn3      && ./install-linux.sh
        cd $ISSM_DIR/externalpackages/petsc      && ./install-3.20-linux.sh
        cd $ISSM_DIR/externalpackages/gsl        && ./install.sh
        cd $ISSM_DIR/externalpackages/codipack   && ./install.sh
        cd $ISSM_DIR/externalpackages/medipack   && ./install.sh
