name: "Prepare External Packages"
inputs:
  build_type:
    required: false
    default: "basic"
    type: string
  externalpackages-cache-hit:
    required: true
    default: false
    type: bool
  ISSM_DIR:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Set ISSM_DIR
      shell: bash
      run: |
        echo $ISSM_DIR
        
    - name: Install External packages 
      if: ${{ ( inputs.build_type == 'basic') && ( inputs.externalpackages-cache-hit != 'true') }}
      shell: bash
      run: |
        cd $ISSM_DIR/externalpackages/triangle && ./install-linux.sh
        cd $ISSM_DIR/externalpackages/m1qn3    && ./install-linux.sh
        cd $ISSM_DIR/externalpackages/petsc    && ./install-3.21-linux.sh
        cd $ISSM_DIR/externalpackages/semic    && ./install.sh

    - name: Install External packages for AD
      if: ${{ ( inputs.build_type == 'codipack') && ( inputs.externalpackages-cache-hit != 'true') }}
      shell: bash
      run: |
        cd $ISSM_DIR/externalpackages/triangle   && ./install-linux.sh
        cd $ISSM_DIR/externalpackages/m1qn3      && ./install-linux.sh
        cd $ISSM_DIR/externalpackages/petsc      && ./install-3.20-linux.sh
        cd $ISSM_DIR/externalpackages/gsl        && ./install.sh
        cd $ISSM_DIR/externalpackages/codipack   && ./install.sh
        cd $ISSM_DIR/externalpackages/medipack   && ./install.sh
