name: Compilation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ISSM_DIR: ${{ github.workspace }}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Installing MATLAB
        id: setup-matlab
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install and Compile ISSM
        env:
          MATLAB_PATH: ${{ steps.setup-matlab.outputs.matlabroot }}
        run: cd .github/ci_scripts && ./ci_ISSM.sh github_linux_basic

      - name: Checking Environment
        run: echo "BEFORE: ${LD_LIBRARY_PATH}" && source $ISSM_DIR/etc/environment.sh && echo "AFTER: ${LD_LIBRARY_PATH}"

      - name: Run ISSM MATLAB test
        uses: matlab-actions/run-command@v2
        with:
          command: matlab_ci

      - run: echo "This job's status is ${{ job.status }}."
