name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ISSM_DIR: ${{ github.action_path }}
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: run jenkins
      run: cd jenkins && ./jenkins.sh ross-debian_linux-basic
