name: Ubuntu CodiPack 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ISSM_DIR: ${{ github.workspace }}

jobs:
  build-test:
    uses: ./.github/workflows/common-workflow.yml 
    with:
      os: ubuntu-latest
      build_type: codipack
    secrets: inherit
    name: build-test-ubuntu-codipack
