name: Ubuntu CodiPack 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  ISSM_DIR: ${{ github.workspace }}

jobs:
  build-test:
    uses: ./.github/workflows/common-workflow.yml 
    with:
      os: ubuntu-latest
      build_type: codipack
      build_command: '
        source $ISSM_DIR/etc/environment.sh
        autoreconf -ivf
        ./configure --prefix=${ISSM_DIR} \
        --enable-tape-alloc \
        --enable-development \
        --enable-debugging \
        --with-numthreads=4 \
        --without-kriging \
        --without-kml \
        --without-Sealevelchange \
        --without-Love \
        --with-matlab-dir=${{ steps.setup-matlab.outputs.matlabroot }} \
        --with-fortran-lib="-L/usr/lib/x86_64-linux-gnu -lgfortran" \
        --with-mpi-include="${ISSM_DIR}/externalpackages/petsc/install/include" \
        --with-mpi-libflags="-L${ISSM_DIR}/externalpackages/petsc/install/lib -lmpi -lmpicxx -lmpifort" \
        --with-blas-lapack-dir="${ISSM_DIR}/externalpackages/petsc/install" \
        --with-metis-dir="${ISSM_DIR}/externalpackages/petsc/install" \
        --with-parmetis-dir="${ISSM_DIR}/externalpackages/petsc/install" \
        --with-scalapack-dir="${ISSM_DIR}/externalpackages/petsc/install" \
        --with-mumps-dir="${ISSM_DIR}/externalpackages/petsc/install" \
        --with-triangle-dir="${ISSM_DIR}/externalpackages/triangle/install" \
        --with-gsl-dir="${ISSM_DIR}/externalpackages/gsl/install" \
        --with-m1qn3-dir="${ISSM_DIR}/externalpackages/m1qn3/install" \
        --with-medipack-dir="${ISSM_DIR}/externalpackages/medipack/install" \
        --with-codipack-dir="${ISSM_DIR}/externalpackages/codipack/install"
        '
      ext_install_command: '
        cd $ISSM_DIR/externalpackages/triangle   && ./install-linux.sh
        cd $ISSM_DIR/externalpackages/m1qn3      && ./install-linux.sh
        cd $ISSM_DIR/externalpackages/petsc      && ./install-3.20-linux.sh
        cd $ISSM_DIR/externalpackages/gsl        && ./install.sh
        cd $ISSM_DIR/externalpackages/codipack   && ./install.sh
        cd $ISSM_DIR/externalpackages/medipack   && ./install.sh
        '
    secrets: inherit
    name: build-test-ubuntu-codipack
